### ISSUE TITLE
Tìm hiểu cơ bản về phinx

### ISSUE THREAD

**Issue by nguyenquang2302** [nguyenquang2302/migrations#1]
- Tạo ra các phiên bản  database dựa trên những thay đổi  thuộc tính, table, dữ liệu trong database..( quá trình phát triển database)

**Comment by nguyenquang2302** [comment]
[Tìm hiểu PHINX.docx](https://github.com/nguyenquang2302/migrations/files/162673/Tim.hi.u.PHINX.docx)

**Comment by khanhicetea** [comment]
:+1: viet kha tot do
